["canons/"]
name = "Canons"
description = "Tags for canons from the Canon Hub and the articles that take place in their setting."

[aces-and-eights]
description = "Of or related to the [https://scp-wiki.wikidot.com/aces-and-eights Aces and Eights] canon."
description-plain = "Of or related to the Aces and Eights canon."

[aiad]
description = "Of or related to the [https://scp-wiki.wikidot.com/aiad-homescreen AIAD] canon."
description-plain = "Of or related to the AIAD canon."

[ad-astra]
description = "Of or related to the [https://scp-wiki.wikidot.com/ad-astra-per-aspera-hub Ad Astra Per Aspera] canon."
description-plain = "Of or related to the Ad Astra Per Aspera canon."

[alchemy-department]
description = "Of or related to [https://scp-wiki.wikidot.com/the-alchemy-department-hub The Alchemy Department] canon."
description-plain = "Of or related to The Alchemy Department canon."

[antarctic-exchange]
description = "Of or related to the [https://scp-wiki.wikidot.com/antarctic-exchange-hub Antarctic Exchange] canon."
description-plain = "Of or related to the Antarctic Exchange canon."

[apotheosis]
description = "Of or related to the [https://scp-wiki.wikidot.com/antarctic-exchange-hub Apotheosis] canon."
description-plain = "Of or related to the Apotheosis canon."

[bellerverse]
description = "Of or related to the [https://scp-wiki.wikidot.com/bellerverse Bellerverse] canon."
description-plain = "Of or related to the Bellerverse canon."

[black-rabbit-company]
description = "Of or related to the [https://scp-wiki.wikidot.com/stealingsolidarityhub Stealing Solidarity] canon."
description-plain = "Of or related to the Stealing Solidarity canon."

[broken-masquerade]
description = "Of or related to the [https://scp-wiki.wikidot.com/broken-masquerade-hub Broken Masquerade] canon."
description-plain = "Of or related to the Broken Masquerade canon."

[competitive-eschatology]
description = "Of or related to the [https://scp-wiki.wikidot.com/Competitive-Eschatology-Hub Competitive Eschatology] canon."
description-plain = "Of or related to the Competitive Eschatology canon."

[cool-war-2]
description = "Of or related to the [https://scp-wiki.wikidot.com/cool-war-2-hub Cool War 2: Ruiz From Your Grave] canon."
description-plain = "Of or related to the Cool War 2: Ruiz From Your Grave canon."

[daybreak]
description = "Of or related to the [https://scp-wiki.wikidot.com/daybreak Daybreak] canon."
description-plain = "Of or related to the Daybreak canon."

[deepwell-catalog]
description = "Of or related to the [https://scp-wiki.wikidot.com/site-17-hub Site-17 Deepwell] canon."
description-plain = "Of or related to the Site-17 Deepwell canon."

[doctors-of-the-church]
description = "Of or related to the [https://scp-wiki.wikidot.com/doctors-of-the-church-hub Doctors of the Church] canon."
description-plain = "Of or related to the Doctors of the Church canon."

["dread&circuses"]
description = "Of or related to the [https://scp-wiki.wikidot.com/dread-circuses-hub Dread and Circuses] canon."
description-plain = "Of or related to the Dread and Circuses canon."

[end-of-death]
description = "Of or related to the [https://scp-wiki.wikidot.com/end-of-death-hub End of Death] canon."
description-plain = "Of or related to the End of Death canon."

[etdp]
description = "Of or related to the [https://scp-wiki.wikidot.com/etdp-hub-page Et Tam Deum Petivi] canon."
description-plain = "Of or related to the Et Tam Deum Petivi canon."

[from-120s-archives]
description = "Of or related to the [https://scp-wiki.wikidot.com/from-120-s-archives-hub From 120's Archives] canon."
description-plain = "Of or related to the From 120's Archives canon."

[green-king]
description = "Of or related to the [https://scp-wiki.wikidot.com/codename-green-king-hub Codename: Green King hub]."
description-plain = "Of or related to the Codename: Green King hub."

[heimdall]
description = "Of or related to [https://scp-wiki.wikidot.com/Project-Heimdall Project Heimdall]."
description-plain = "Of or related to Project Heimdall."

[insect-hell]
description = "Of or related to the [https://scp-wiki.wikidot.com/arbh-class-hub Insect Hell] canon."
description-plain = "Of or related to the Insect Hell canon."

[lolfoundation]
description = "Of or related to the [https://scp-wiki.wikidot.com/lolfoundation-hub-page lolFoundation] canon."
description-plain = "Of or related to the lolFoundation canon."

[man-who-wasnt-there]
description = "Of or relating to [https://scp-wiki.wikidot.com/the-man-who-wasnt-there-hub The Man Who Wasn't There] canon."
description-plain = "Of or relating to The Man Who Wasn't There canon."

[memoria-adytum]
description = "Of or related to the [https://scp-wiki.wikidot.com/memoria-adytum In Memoria, Adytum] canon."
description-plain = "Of or related to the In Memoria, Adytum canon."

[nightfall]
description = "Of or related to the [https://scp-wiki.wikidot.com/nightfall-hub Nightfall] canon."
description-plain = "Of or related to the Nightfall canon."

[no-return]
description = "Of or related to the [https://scp-wiki.wikidot.com/no-return-hub No Return] canon."
description-plain = "Of or related to the No Return canon."

[old-man-in-the-sea]
description = "Of or related to the [https://scp-wiki.wikidot.com/old-man-in-the-sea-hub Old Man in the Sea] canon."
description-plain = "Of or related to the Old Man in the Sea canon."

[on-guard-43]
description = "Of or related to the [https://scp-wiki.wikidot.com/on-guard-43-hub On Guard 43] canon."
description-plain = "Of or related to the On Guard 43 canon."

[on-mount-golgotha]
description = "Of or related to the [https://scp-wiki.wikidot.com/on-mount-golgotha-hub On Mount Golgotha] canon."
description-plain = "Of or related to the On Mount Golgotha canon."

[only-game-in-town]
description = "Of or related to the [https://scp-wiki.wikidot.com/only-game-in-town-hub Only Game in Town] canon."
description-plain = "Of or related to the Only Game in Town canon."

[orcadia]
description = "Of or related to the Seas of Orcadia canon."

[pitch-haven]
description = "Of or related to the [https://scp-wiki.wikidot.com/pitch-haven-hub Pitch Haven] canon."
description-plain = "Of or related to the Pitch Haven canon."

[rats-nest]
description = "Of or related to the [https://scp-wiki.wikidot.com/rat-s-nest-hub Rat's Nest] canon."
description-plain = "Of or related to the Rat's Nest canon."

[resurrection]
description = "Of or related to the [https://scp-wiki.wikidot.com/resurrection Resurrection] project."
description-plain = "Of or related to the Resurrection project."

["s&c-plastics"]
description = "Of or related to the [https://scp-wiki.wikidot.com/the-s-c-plastics-hub S & C Plastics] canon."
description-plain = "Of or related to the S & C Plastics canon."

[ship-in-a-bottle]
description = "Of or related to the [https://scp-wiki.wikidot.com/siabhub Ship In A Bottle] canon."
description-plain = "Of or related to the Ship In A Bottle canon."

[sotm]
description = "Of or related to the [https://scp-wiki.wikidot.com/sotmhub Straight On Till Morning] canon."
description-plain = "Of or related to the Straight On Till Morning canon."

[the-coldest-war]
description = "Of or related to the [https://scp-wiki.wikidot.com/the-coldest-war-hub Coldest War] canon."
description-plain = "Of or related to the Coldest War canon."

[the-gulf]
description = "Of or related to [https://scp-wiki.wikidot.com/The-Gulf The Gulf] canon."
description-plain = "Of or related to The Gulf canon."

[the-trashfire]
description = "Of or relating to [https://scp-wiki.wikidot.com/the-trashfire The Trashfire] canon."
description-plain = "Of or relating to The Trashfire canon."

[third-law]
description = "Of or pertaining to the [https://scp-wiki.wikidot.com/third-law-hub Third Law] canon."
description-plain = "Of or pertaining to the Third Law canon."

[twisted-pines]
description = "Of or related to the [https://scp-wiki.wikidot.com/those-twisted-pines-hub Those Twisted Pines] canon."
description-plain = "Of or related to the Those Twisted Pines canon."

[unfounded]
description = "Of or related to the [https://scp-wiki.wikidot.com/unfounded-hub Unfounded] canon."
description-plain = "Of or related to the Unfounded canon."

[unhuman]
description = "Of or related to the [https://scp-wiki.wikidot.com/unhuman-hub UnHuman] canon."
description-plain = "Of or related to the UnHuman canon."

[war-on-all-fronts]
description = "Of or related to the [https://scp-wiki.wikidot.com/war-on-all-fronts-hub War On All Fronts] canon."
description-plain = "Of or related to the War On All Fronts canon."

[wonderful-world]
description = "Of or related to the [https://scp-wiki.wikidot.com/wonder-world What a Wonderful World] canon."
description-plain = "Of or related to the What a Wonderful World canon."
