["characters/"]
name = "Characters"
description = "Tags indicating that a specific character has a significant presence within the article. Divided into Foundation Employees, SCP Objects, and Persons of Interest."

[[section]]
name = "Foundation Employees"
description = "Employees of the Foundation."

[section.8-ball]
description = "8-ball, aka 8B-A1, an artificial intelligence."

[section.aaron-siegel]
description = "Aaron Siegel, O5-1."

[section.agent-adams]
description = "Agent Andrea Adams."

[section.agent-green]
description = "Agent Green."

[section.agent-kazmarek]
description = "Agent Travis Kazmarek."

[section.agent-laferrier]
description = "Agent V.A. LaFerrier."

[section.agent-lament]
description = "Agent Troy Lament."

[section.agent-lurk]
description = "Agent Dietrich M. Lurk."

[section.agent-merlo]
description = "Agent Sasha Merlo."

[section.agent-navarro]
description = "Agent Daniel Navarro."

[section.agent-popescu]
description = "Agent Lucretia Popescu."

[section.agent-strelnikov]
description = "Agent Dmitri Strelnikov."

[section.agent-trauss]
description = "Agent Trauss, aka C-51174."

[section.agent-yoric]
description = "Agent Yoric Elroy, aka Jack \"Poor Yoric\" Dawkins."

[section.alexandra]
description = "Alexandra, an artificial intelligence."

[section.alex-thorley]
description = "Alex Thorley of the Department of Unreality ."

[section.bailey-brothers]
description = "Tristan, Thomas and Trevor Bailey."

[section.d-7294]
description = "D-7294."

[section.d-11424]
description = "D-11424."

[section.director-aktus]
description = "Director Aktus."

[section.director-bold]
description = "Director Cal Bold of the Decommissioning Department."

[section.director-diaghilev]
description = "Director Ruslav Diaghilev of the Alchemy Department."

[section.director-gillespie]
description = "Director Gillespie."

[section.director-mcinnis]
description = "Dr. Allan J. McInnis, Director of Site-43."

[section.director-mctiriss]
description = "Director Kate McTiriss."

[section.director-moose]
description = "Director Moose."

[section.director-lague]
description = "Director Paul Lague, of the Integration Program and Site-322."

[section.django-bridge]
description = "Django Bridge."

[section.doctor-asheworth]
description = "Dr. Daniel Asheworth."

[section.doctor-blank]
description = "Dr. Harold R. Blank."

[section.doctor-bright]
description = "Dr. Bright."

[section.doctor-cimmerian]
description = "Dr. Cimmerian."

[section.doctor-clef]
description = "Dr. Alto Clef."

[section.doctor-dan]
description = "Dr. Dan ███████, of SCP-096."

[section.doctor-edison]
description = "Dr. Michael Edison."

[section.doctor-elliott]
description = "Dr. Chelsea Elliott."

[section.doctor-everwood]
description = "Dr. Everwood, GOI specialist."

[section.doctor-fynegan]
description = "Dr. Fynegan."

[section.doctor-gears]
description = "Dr. Gears."

[section.doctor-gerald]
description = "Dr. Gerald."

[section.doctor-glass]
description = "Dr. Simon Glass."

[section.doctor-heiden]
description = "Dr. Frederick Heiden."

[section.doctor-hoygull]
description = "Dr. Hoygull, Avian Division."

[section.doctor-iceberg]
description = "Dr. Iceberg."

[section.doctor-king]
description = "Dr. King."

[section.doctor-kondraki]
description = "Dr. Kondraki."

[section.doctor-light]
description = "Dr. Sophia N. Light."

[section.doctor-lillihammer]
description = "Dr. Lillian S. Lillihammer."

[section.doctor-mann]
description = "Dr. Everett Mann."

[section.doctor-mcdoctorate]
description = "Dr. Placeholder McDoctorate, previously known as Director Nathan Valis."

[section.doctor-reynders]
description = "Dr. Ilse Reynders."

[section.doctor-rights]
description = "Dr. Rights."

[section.doctor-rivera]
description = "Dr. Jessie Rivera."

[section.doctor-roget]
description = "Dr. Ralph Roget."

[section.doctor-sinclair]
description = "Dr. Katherine Sinclair."

[section.doctor-sokolsky]
description = "Dr. Daniil Sokolsky."

[section.doctor-sorts]
description = "Dr. Johannes Sorts."

[section.doctor-thereven]
description = "Doctor Cole Thereven."

[section.doctor-vang]
description = "Dr. S. Vang."

[section.doctor-wettle]
description = "Dr. William Wallace Wettle."

[section.draven-kondraki]
description = "Dr./Director Draven Kondraki."

[section.general-bowe]
description = "General Bowe."

[section.glacon]
description = "Glacon.aic, an artificial intelligence."

[section.judith-low]
description = "Dr. Judith Low, Department of History."

[section.kain-pathos-crow]
description = "Professor Kain Pathos Crow."

[section.lombardi]
description = "[https://scp-wiki.wikidot.com/the-lombardi-tales Agent Lombardi]."
description-plain = "Agent Lombardi."

[section.maria-jones]
description = "Maria Jones, of RAISA."

[section.marion-wheeler]
description = "Marion Wheeler, of the Antimemetics Division."

[section.mark-kiryu]
description = "Mark Kiryu of Kiryu Labs."

[section.philip-deering]
description = "Philip E. Deering, formerly [https://scp-wiki.wikidot.com/scp-5056 SCP-5056-B]."
description-plain = "Philip E. Deering, formerly SCP-5056-B."

[section.professor-bjornsen]
description = "Professor Anders Bjornsen."

[section.researcher-conwell]
description = "Researcher Jacob Conwell."

[section.researcher-james]
description = "Junior Researcher James, best foundation researcher ever! (Age 5)."

[section.researcher-labelle]
description = "Researcher Rose Labelle."

[section.researcher-lloyd]
description = "Researcher Lloyd, Destroyer of Worlds."

[section.researcher-rosen]
description = "Researcher David Rosen."

[section.researcher-smalls]
description = "Researcher Adamo Smalls."

[section.researcher-talloran]
description = "Researcher Talloran."

[section.riven-mercer]
description = "Riven Mercer of Kiryu Labs."

[section.sheldon-katz]
description = "Sheldon Katz, of the Legal Department."

[section.simon-pietrykau]
description = "Simon Pietrykau, of the Department of Analytics."

[section.thad-xyank]
description = "Dr. Thaddeus \"Thad\" Xyank, of the Department of Temporal Anomalies."

[section.the-administrator]
description = "The Administrator (as a separate entity from the O5 Council)."

[section.zyn-kiryu]
description = "Researcher Zyn Kiryu."

[[section]]
name = "SCP Objects"
description = "SCP Objects with their own character tags."

[section.able]
description = "Able, aka [https://scp-wiki.wikidot.com/scp-076 SCP-076-2]."
description-plain = "Able, aka SCP-076-2."

[section.alexei-belitrov]
description = "Alexei Belitrov, aka [https://scp-wiki.wikidot.com/scp-2273 SCP-2273]."
description-plain = "Alexei Belitrov, aka SCP-2273."

[section.alleged-god]
description = "\"God\", aka [https://scp-wiki.wikidot.com/scp-343 SCP-343]."
description-plain = "\"God\", aka SCP-343."

[section.blackwood]
description = "[https://scp-wiki.wikidot.com/new Lord Blackwood, Explorer and Gentleman], aka [https://scp-wiki.wikidot.com/scp-1867 SCP-1867]."
description-plain = "Lord Blackwood, Explorer and Gentleman, aka SCP-1867."

[section.bobble-the-clown]
description = "Bobble The Clown, aka [https://scp-wiki.wikidot.com/scp-993 SCP-993]."
description-plain = "Bobble The Clown, aka SCP-993."

[section.bones]
description = "Bones, aka [https://scp-wiki.wikidot.com/scp-2721 SCP-2721-LORD] or Eli."
description-plain = "Bones, aka SCP-2721-LORD or Eli."

[section.cain]
description = "Cain, aka [https://scp-wiki.wikidot.com/scp-073 SCP-073]."
description-plain = "Cain, aka [https://scp-wiki.wikidot.com/scp-073 SCP-073]."

[section.cousin-johnny]
description = "Cousin Johnny, aka [https://scp-wiki.wikidot.com/scp-2852 SCP-2852]."
description-plain = "Cousin Johnny, aka SCP-2852."

[section.doctor-spanko]
description = "[https://scp-wiki.wikidot.com/doctor-spanko-hub Dr. Spanko], aka [https://scp-wiki.wikidot.com/scp-2337 SCP-2337]."
description-plain = "Dr. Spanko, aka SCP-2337."

[section.donkman]
description = "Ulysses B. Donkman, aka [https://scp-wiki.wikidot.com/scp-4768 SCP-4768]."
description-plain= "Ulysses B. Donkman, aka SCP-4768"

[section.fred]
description = "Fred, aka [https://scp-wiki.wikidot.com/scp-423 SCP-423]."
description-plain = "Fred, aka SCP-423."

[section.grabnok]
description = "Grabnok the Destroyer, the Reluctant Dimension Hopper, aka [https://scp-wiki.wikidot.com/scp-507 SCP-507]."
description-plain = "Grabnok the Destroyer, the Reluctant Dimension Hopper, aka SCP-507."

[section.hard-to-kill-reptile]
description = "The \"Hard-To-Destroy Reptile\", aka [https://scp-wiki.wikidot.com/scp-682 SCP-682]."
description-plain = "The \"Hard-To-Destroy Reptile\", aka SCP-682."

[section.heather-mason]
description = "Heather Mason, aka \"Ms. Mad About Video Games\" or [https://scp-wiki.wikidot.com/scp-3090 SCP-3090]."
description-plain = "Heather Mason, aka \"Ms. Mad About Video Games\" or SCP-3090."

[section.hogslice]
description = "Hogslice, aka [https://scp-wiki.wikidot.com/scp-6599 SCP-6599]."
description-plain = "Hogslice, aka SCP-6599."

[section.iris-thompson]
description = "Iris Thompson, aka [https://scp-wiki.wikidot.com/scp-105 SCP-105]."
description-plain = "Iris Thompson, aka SCP-105."

[section.leslie]
description = "Leslie, instance of [https://scp-wiki.wikidot.com/scp-3774 SCP-3774]."
description-plain = "Leslie, instance of SCP-3774."

[section.moon-champion]
description = "Moon Champion, aka Champion of the Moon or [https://scp-wiki.wikidot.com/scp-1233 SCP-1233]."
description-plain = "Moon Champion, aka Champion of the Moon or SCP-1233."

[section.mr-fish]
description = "Mr. Fish, Little Mister from Dr. Wondertainment, aka [https://scp-wiki.wikidot.com/scp-527 SCP-527]."
description-plain = "Mr. Fish, Little Mister from Dr. Wondertainment, aka SCP-527."

[section.old-ai]
description = "\"Old AI\", aka [https://scp-wiki.wikidot.com/scp-079 SCP-079]."
description-plain = "\"Old AI\", aka SCP-079."

[section.plague-doctor]
description = "The Plague Doctor, aka [https://scp-wiki.wikidot.com/scp-049 SCP-049]."
description-plain = "The Plague Doctor, aka SCP-049."

[section.possessive-mask]
description = "The Possessive Mask, aka [https://scp-wiki.wikidot.com/scp-035 SCP-035]."
description-plain = "The Possessive Mask, aka SCP-035."

[section.rainer-miller]
description = "Rainer Miller, aka [https://scp-wiki.wikidot.com/scp-4051 SCP-4051]."
description-plain = "Rainer Miller, aka SCP-4051."

[section.sauelsuesor]
description = "Sauelsuesor, aka [https://scp-wiki.wikidot.com/scp-179 SCP-179]."
description-plain = "Sauelsuesor, aka SCP-179."

[section.shy-guy]
description = "The Shy Guy, aka [https://scp-wiki.wikidot.com/scp-096 SCP-096]."
description-plain = "The Shy Guy, aka SCP-096."

[section.sigurros]
description = "Sigurrós Stefánsdóttir, aka [https://scp-wiki.wikidot.com/scp-239 SCP-239]."
description-plain = "Sigurrós Stefánsdóttir, aka SCP-239."

[section.ten-dots]
description = "[https://scp-wiki.wikidot.com/scp-2521 SCP-2521]."
description-plain = "SCP-2521."

[section.the-old-man]
description = "The Old Man, aka [https://scp-wiki.wikidot.com/scp-106 SCP-106]."
description-plain = "The Old Man, aka SCP-106."

[section.the-sculpture]
description = "The Sculpture, aka [https://scp-wiki.wikidot.com/scp-173 SCP-173]."
description-plain = "The Sculpture, aka SCP-173."

[section.the-specter]
description = "The Specter, aka [https://scp-wiki.wikidot.com/scp-4944 SCP-4944]."
description-plain = "The Specter, aka SCP-4944."

[[section]]
name = "Persons of Interest"
description = "Other individuals involved in the anomalous."

[section.aldon]
description = "Aldon, an anartist."

[section.big-cheese-horace]
description = "Big Cheese Horace of the Fifthists"

[section.brainy-brian]
description = "Brainy Brian of Wondertainment/MC&D, also known as \"Doctor Neurosis\"."

[section.chaz-ambrose]
description = "Chaz Ambrose, founder of Ambrose Restaurants."

[section.dado]
description = "[https://scp-wiki.wikidot.com/dado-hub dado] is taking care of u in dis one. u no worry."
description-plain = "dado is taking care of u in dis one. u no worry."

[section.damien-nowak]
description = "Damien Nowak, cult leader."

[section.dc-al-fine]
description = "D.C. al Fine, Undersecretary-General of the Global Occult Coalition."

[section.eric]
description = "Eric, a mysterious creator of anomalies."

[section.esther-kogan]
description = "Esther Kogan, aka lesbian_gengar of Gamers Against Weed."

[section.faeowynn-wilson]
description = "Faeowynn \"Fae\" Wilson, of Wilson's Wildlife Solutions."

[section.finnegan]
description = "Finnegan, anartist."

[section.grand-karcist-ion]
description = "Grand Karcist Ion, founder of Sarkicism."

[section.halyna-ieva]
description = "Karcist Halyna Ieva, aka [https://scp-wiki.wikidot.com/mother-who-demands-ones-toes The Mother Who Demands One's Toes]."
description-plain = "Karcist Halyna Ieva, aka The Mother Who Demands One's Toes."

[section.hanged-king]
description = "The Hanged King of Alagadda."

[section.holly-light]
description = "Holly Light, of Dr Wondertainment."

[section.icky]
description = "Veronica Mason, aka [https://scp-wiki.wikidot.com/icky-the-magic-clown Icky the Magic Clown] of Herman Fuller's Circus of the Disquieting."
description-plain = "Veronica Mason, aka Icky the Magic Clown of Herman Fuller's Circus of the Disquieting."

[section.iris-dark]
description = "Iris Dark, of Marshall, Carter & Dark Ltd."

[section.isabel-v]
description = "Isabel Helga Anastasia Parvati Wondertainment V."

[section.jockjamsvol6]
description = "JJ, aka jockjamsvol6 of Gamers Against Weed."

[section.jude-kriyot]
description = "Jude Kriyot, aka bluntfiend of Gamers Against Weed."

[section.judy-papill]
description = "Judy Papill, aka Judy the Tongue of Doctor Wondertainment."

[section.kenneth-spencer]
description = "Kenneth Spencer, of the FBI Unusual Investigations Unit."

[section.kindness]
description = "A kind man."

[section.legate-trunnion]
description = "Legate Trunnion, prophet of the Cogwork Orthodoxy."

[section.lewitt-zairi-family]
description = "The Lewitt Zairi Family, of the Horizon Initiative."

[section.manny]
description = "Manny, aka The Man With the Upside Down Face of Herman Fuller's Circus of the Disquieting."

[section.nadox]
description = "Nadox, one of the four Klavigars of Sarkicism."

[section.orok]
description = "Orok, one of the four Klavigars of Sarkicism."

[section.pangloss]
description = "Pangloss, mythical figure and leaver of notes."

[section.polaricecraps]
description = "Polaricecraps, of Gamers Against Weed."

[section.queen-mab]
description = "Queen Mab, a Fae tyrant and goddess."

[section.professor-aw]
description = "Professor A.W., inventor and creator of curiosities."

[section.richard-chappell]
description = "Richard Davis Chappell, founder of the Chicago Spirit."

[section.robert-bumaro]
description = "Robert Bumaro, prophet of Mekhane."

[section.robin-thorne]
description = "Robin Thorne, of the FBI Unusual Investigations Unit."

[section.ruiz-duchamp]
description = "Ruiz Duchamp, an anartist."

[section.saint-hedwig]
description = "Saint Hedwig, a prophet of Maxwellism."

[section.saturn-deer]
description = "Saturn Deer, serial reincarnator and false prophet."

[section.the-engineer]
description = "The Engineer, of the Chaos Insurgency."

[section.the-critic]
description = "The Critic, of Are We Cool Yet."

[section.thilo-zwist]
description = "Thilo Zwist, memeticist."

[section.tim-wilson]
description = "Tim Wilson, of Wilson's Wildlife Solutions."

[section.veronica-fitzroy]
description = "Veronica Katherine Fitzroy, anartist/D-class."

[section.vincent-anderson]
description = "Vincent Anderson, of Anderson Robotics."
