["characters/"]
name = "Characters"
description = "Tags indicating that a specific character has a significant presence within the article. See [http://www.scp-wiki.net/forum/t-1938874/character-tags this thread] for further details."

[51174]
description = "51174"

[aaron-siegel]
description = "Aaron Siegel"

[able]
description = "Able, or SCP-076"

[agent-green]
description = "Agent Green"

[agent-kazmarek]
description = "Agent Travis Kazmarek"

[agent-laferrier]
description = "Agent V.A. LaFerrier"

[agent-lament]
description = "Agent Troy Lament"

[agent-merlo]
description = "Agent Sasha Merlo"

[agent-navarro]
description = "Agent Daniel Navarro"

[agent-strelnikov]
description = "Agent Dmitri Strelnikov"

[agent-yoric]
description = "Agent Yoric Elroy, aka Jack "Poor Yoric" Dawkins"

[alexandra]
description = "Alexandra, AI unit"

[alexei-belitrov]
description = "Alexei Belitrov, or SCP-2273"

[aldon]
description = "Aldon"

[big-cheese-horace]
description = "Big Cheese Horace of the Fifthists"

[bobble-the-clown]
description = "Bobble The Clown, or SCP-993"

[bones]
description = "Bones, aka SCP-2721-LORD or Eli"

[brainy-brian]
description = "Brainy Brian of Wondertainment/MC&D, also known as 'Doctor Neurosis'"

[chaz-ambrose]
description = "Chaz Ambrose, founder of Ambrose Restaraunts"

[cousin-johnny]
description = "Cousin Johnny, or SCP-2852"

[d-11424]
description = "D-11424"

[dado]
description = "dado is taking care of u in dis one. u no worry. "

[director-aktus]
description = "Director Aktus"

[director-bold]
description = "Director Cal Bold of the Decommissioning Department"

[director-gillespie]
description = "Director Gillespie"

[director-mctiriss]
description = "Director Kate McTiriss"

[director-moose]
description = "Director Moose"

[django-bridge]
description = "Django Bridge"

[draven-kondraki]
description = "Dr./Director Draven Kondraki"

[doctor-bright]
description = "Dr. Bright"

[doctor-cimmerian]
description = "Dr. Cimmerian"

[doctor-clef]
description = "Dr. Alto Clef"

[doctor-dan]
description = "Dr. Dan ███████, of SCP-096"

[doctor-edison]
description = "Dr. Michael Edison"

[doctor-everwood]
description = "Dr. Everwood, GOI specialist"

[doctor-fynegan]
description = "Dr. Fynegan"

[doctor-gears]
description = "Dr. Gears"

[doctor-gerald]
description = "Dr. Gerald"

[doctor-glass]
description = "Dr. Simon Glass"

[doctor-heiden]
description = "Dr. Frederick Heiden"

[doctor-hoygull]
description = "Doctor Hoygull, Avian Division"

[doctor-iceberg]
description = "Dr. Iceberg"

[doctor-king]
description = "Dr. King"

[doctor-kondraki]
description = "Dr. Kondraki"

[doctor-light]
description = "Dr. Sophia N. Light"

[doctor-mann]
description = "Dr. Everett Mann"

[doctor-rights]
description = "Dr. Rights"

[doctor-roget]
description = "Dr. Ralph Roget"

[doctor-sorts]
description = "Dr. Johannes Sorts"

[doctor-spanko]
description = "Dr. Spanko"

[doctor-vang]
description = "Dr. S. Vang "

[donkman]
description = "Ulysses B. Donkman"

[eric]
description = "Eric, a mysterious character"

[faeowynn-wilson]
description = "Faeowynn "Fae" Wilson"

[fred]
description = "Fred, or SCP-423"

[finnegan]
description = "Finnegan"

[general-bowe]
description = "General Bowe"

[glacon]
description = "Glacon.aic"

[grand-karcist-ion]
description = "Grand Karcist Ion, a Sarkic figure"

[hanged-king]
description = "Of or relating to the Hanged King."

[halyna-ieva]
description = "Karcist Halyna Ieva, aka The Mother Who Demands One's Toes"

[heather-mason]
description = "Heather Mason, AKA "Ms. Mad About Video Games"/"SCP-3090"."

[holly-light]
description = "Holly Light"

[iris-dark]
description = "Iris Dark"

[iris-thompson]
description = "Iris Thompson, aka SCP-105"

[isabel-v]
description = "Isabel Helga Anastasia Parvati Wondertainment V "

[kain-pathos-crow]
description = "Professor Kain Pathos Crow"

[kenneth-spencer]
description = "Kenneth Spencer"

[jude-kriyot]
description = "Jude Kriyot, AKA bluntfiend of Gamers Against Weed"

[judy-papill]
description = "Judy Papill, AKA Judy the Tongue"

[kindness]
description = "A kind man"

[leslie]
description = "Leslie, instance of SCP-3774"

[lewitt-zairi-family]
description = "The Lewitt Zairi Family"

[lombardi]
description = "[http://scp-wiki.wikidot.com/the-lombardi-tales Agent Lombardi]"

[maria-jones]
description = "Maria Jones of RAISA"

[marion-wheeler]
description = "Marion Wheeler"

[mark-kiryu]
description = "Mark Kiryu of Kiryu Labs"

[moon-champion]
description = "Moon Champion, Champion of the Moon and SCP-1233"

[mr-fish]
description = "Mr. Fish, Little Mister from Dr. Wondertainment and SCP-527"

[plague-doctor]
description = "The Plague Doctor, aka SCP-049"

[researcher-conwell]
description = "Researcher Jacob Conwell"

[researcher-james]
description = "Junior Researcher James, best foundation researcher ever! (Age 5)"

[researcher-labelle]
description = "Researcher Rose Labelle"

[researcher-lloyd]
description = "Researcher Lloyd, Destroyer of Worlds"

[researcher-rosen]
description = "Researcher David Rosen"

[researcher-smalls]
description = "Researcher Adamo Smalls"

[researcher-talloran]
description = "Researcher Talloran"

[riven-mercer]
description = "Riven Mercer of Kiryu Labs"

[robert-bumaro]
description = "Robert Bumaro, a prophet of Mekhane"

[robin-thorne]
description = "Robin Thorne"

[ruiz-duchamp]
description = "Ruiz Duchamp, an anartist"

[saturn-deer]
description = "Saturn Deer"

[scarlet-king]
description = "The Scarlet King"

[sheldon-katz]
description = "Sheldon Katz"

[simon-pietrykau]
description = "Simon Pietrykau"

[thad-xyank]
description = "Dr. Thaddeus \"Thad\" Xyank"

[the-administrator]
description = "The Administrator (as a separate entity from the O5 Council)"

[veronica-fitzroy]
description = "Veronica Katherine Fitzroy, anartist/d-class"

[zyn-kiryu]
description = "Researcher Zyn Kiryu"

