["major/"]
name = "Major Page Tags"
description = "Miscellaneous major page tags that are not top-level tags."

[joke]
description = "Pages which are considered 'jokes' or explicitly 'out-of-universe'. Joke pages can be parodies of any page type, and should also be tagged as such a page usually would. See [https://scp-wiki.wikidot.com/joke-scps Joke SCPs] for more information on Joke pages."
description-plain = "Used for pages which are considered 'jokes' or explicitly 'out-of-universe'. These can be parodies of any page type."

[poetry]
description = "Applicable if the page consists significantly of a form of poetry, with elements such as meter and rhyme."

[archived]
description = "Pages which have been archived due to having been superseded, obsoleted, or inactivity. These pages should also be moved to the {{archived:}} category so they retain the 'archived page' notice and are locked from edits. See [https://scp-wiki.wikidot.com/archived-scps Archived Pages] for more information on archival."
description-plain = "Used for pages which have been archived due to having been superseded, obsoleted, or inactivity."

[explained]
description = "[https://scp-wiki.wikidot.com/scp-ex Explained] SCPs are a special sub-type of //scp//, and should be added to -EX articles as appropriate. Explained articles should also be tagged with their standard object class tag, or //esoteric-class// if the format does not specify a standard object class."
description-plain = "Used for explained SCP articles."
requires = [ "scp" ]

[decommissioned]
description = "Indicates the SCP has been destroyed in-universe upon article deletion out-of-universe. This is no longer in practice, see [https://scp-wiki.wikidot.com/archived:decommissioned-scps Decommissioned SCPs] for more details."
description-plain = "Indicates the SCP has been destroyed in-universe upon article deletion out-of-universe."
requires = [ "scp" ]

[001-proposal]
description = "This is the tag for the articles proposing a possible [https://scp-wiki.wikidot.com/scp-001 SCP-001] object. SCPs tagged with this tag should also be tagged with their standard object class tag, or //esoteric-class// if applicable."
description-plain = "Used for articles proposing a possible SCP-001 object."
similar = [ "scp" ]

[creepypasta]
description = "//creepypasta// are fiction that are unrelated to the SCP Foundation, and usually take the form of urban myths or campfire stories. Creepypasta is only appropriate for the SCP website if it's an original //creepypasta// by the posting author; we are not a repository for unattributed //creepypasta//."
description-plain = "Used for fiction unrelated to the SCP Foundation, and usually take the form of urban myths or campfire stories."
requires = ["tale"]

[collaboration]
description = "//collaboration// pages are those pages that are or were open to additions from any member, with the caveat that staff and the original author reserve the right to modify or delete entries found to be subpar, or close entries entirely."
description-plain = "Used for pages which are or were previously open to additions from any member, with the caveat that staff and the original author reserve the right to modify or delete entries found to be subpar."

[co-authored]
description = "//co-authored// pages are the result of two or more authors working together, but are not open to additions from other members (unless otherwise specified)."
description-plain = "Used for pages which are the result of two or more authors working together, but are not open to additions from other members."

[contest]
description = "//contest// pages are pages created for the purpose of community contests. This should be used in conjunction with //hub// in the case of entry listings, and should not be used on the entries themselves. These contests are only created by staff or with staff permission."
description-plain = "Used for pages which are created for community contests."
requires = [ "hub" ]

[required]
description = "//required// pages are guides that are part of the required reading for joining the SCP Wiki."
description-plain = "Used for pages which are part of the required reading for joining the SCP Wiki."

[_tale-hub]
description = "Utilized in conjunction with the //hub// tag to designate that this hub represents a series that consists mostly or entirely of //tale// articles."
description-plain = "Used for hubs which represent a series that consists mostly or entirely of tale articles."
requires = [ "hub" ]

[[section]]
name = "Supplement pages"
description = "Tags that describe the content of a //supplement// page."

[section.experiment]
description = "This supplement contains primarily experiment logs (see: [https://scp-wiki.wikidot.com/SCP-914 SCP-914] >> [https://scp-wiki.wikidot.com/Experiment-Log-914 Experiment Log 914]). This tag **should not** be used on //scp// pages, even if they have extensive experiment logs."
description-plain = "Used for supplements containing primarily experiment logs."
requires = [ "supplement" ]

[section.exploration]
description = "This supplement contains primarily exploration logs. This tag **should not** be used on //scp// pages, even if they have extensive exploration logs."
description-plain = "Used for supplements containing primarily exploration logs."
requires = [ "supplement" ]

[section.incident]
description = "This supplement contains primarily incident logs or transcripts (see: [https://scp-wiki.wikidot.com/SCP-555 SCP-555] >> [https://scp-wiki.wikidot.com/Incident-Log-555-1 Incident Log 555-1]). This tag **should not** be used on //scp// pages, even if they have extensive incident logs."
description-plain = "Used for supplements containing primarily incident logs or transcripts."
requires = [ "supplement" ]

[section.interview]
description = "This supplement contains primarily interview transcripts (see: [https://scp-wiki.wikidot.com/SCP-277 SCP-277] >> [https://scp-wiki.wikidot.com/277interview Interview 277-A]). This tag **should not** be used on //scp// pages, even if they have extensive interview transcripts."
description-plain = "Used for supplements containing primarily interview transcripts."
requires = [ "supplement" ]

