["object-classes/"]
name = "Object Classes"
description = "All SCP articles tagged as scp should also be tagged with the appropriate tag for their object class or esoteric-class if it does not have one, if its object class cannot be determined from the article's contents, or if it has a non-standard object class. Legacy articles that are dual-classed (such as safe/euclid) are tagged with both of their constituent classes; however, as this is no longer allowed, it is only for posterity until all such articles are updated or deleted."
requires = [ "scp" ]
max = 1

[safe]
description = "SCP is Safe."

[euclid]
description = "SCP is Euclid."

[keter]
description = "SCP is Keter."

[thaumiel]
description = "SCP is Thaumiel."

[neutralized]
description = "SCP is neutralized."

[esoteric-class]
description = "SCP has an object class other than one of the above."
