["series/"]
name = "Series"
description = "Tags for tale and SCP series, that may or may not have a Hub."

[abcs-of-death]
description = "Part of the ABC's of Death [https://scp-wiki.wikidot.com/scp-anthology-hub anthology]."
description-plain = "Part of the ABC's of Death anthology"

[anabasis]
description = "Of or related to the [https://scp-wiki.wikidot.com/anabasis-hub Anabasis] stories."
description-plain = "Of or related to the Anabasis stories."

[ao-tale]
description = "Of or related to the [https://scp-wiki.wikidot.com/ao-hub Tales of Anomalous Items] stories."
description-plain = "Articles based on an anomalous object."

[bury-the-survivors]
description = "Of or related to the [https://scp-wiki.wikidot.com/bury-the-survivors-hub Bury the Survivors] series."
description-plain = "Of or related to the Bury the Survivors series."

[classical-revival]
description = "Of or related to the [https://scp-wiki.wikidot.com/classicalrevivalindex Classical Revival] stories."
description-plain = "Of or related to the Classical Revival stories."

[collector-tale]
description = "Of or related to the Tales of Mr. Collector. (See also: //[https://scp-wiki.wikidot.com/system:page-tags/tag/mister mister]//)."
description-plain = "Of or related to the Tales of Mr. Collector."

[goc-casefiles]
description = "Of or related to the [https://scp-wiki.wikidot.com/goc-hub-page#toc111 Global Occult Coalition Casefiles] stories."
description-plain = "Of or related to the Global Occult Coalition Casefiles stories."

[integration-program]
description = "Of or related to the [https://scp-wiki.wikidot.com/integration-program-hub Integration Program] series."
description-plain = "Of or related to the Integration Program series."

[kiryu-labs]
description = "Of or related to the [https://scp-wiki.wikidot.com/kiryu-labs-hub Kiryu Labs] series."
description-plain = "Of or related to the Kiryu Labs series."

[mister]
description = "Of or related to the \"Little Misters\" series of anomalous individuals."

[new-faces]
description = "Of or related to the [https://scp-wiki.wikidot.com/resurrection-new-faces-hub Resurrection: New Faces] series."
description-plain = "Of or related to the Resurrection: New Faces series."

[old-foes]
description = "Of or related to the [resurrection-old-foes-hub Resurrection: Old Foes] series."
description-plain = "Of or related to the Resurrection: Old Foes series."

[olympia]
description = "Of or related to the [https://scp-wiki.wikidot.com/Olympia-Project Olympia Project]."
description-plain = "Of or related to the Olympia Project."

[orientation]
description = "Of or related to the Orientation series."

[palisade]
description = "Of the [https://scp-wiki.wikidot.com/project-palisade Project Palisade] series."
description-plain = "Of the Project Palisade series."

[project-crossover]
description = "Of or related to [https://scp-wiki.wikidot.com/crossoverprojectindex Project Crossover]."
description-plain = "Of or related to Project Crossover."

[project-thaumiel]
description = "Of or related to [https://scp-wiki.wikidot.com/thaumiel Project Thaumiel]."
description-plain = "Of or related to Project Thaumiel."

[team-bird]
description = "Of or related to [https://scp-wiki.wikidot.com/bird Team Bird]."
description-plain = "Of or related to Team Bird."

[time-after-time-password]
description = "Of or related to the [https://scp-wiki.wikidot.com/the-time-after-time-password-hub Time After Time Password] series."
description-plain = "Of or related to the Time After Time Password series."

[we-meet-again]
description = "Of or related to the [https://scp-wiki.wikidot.com/and-every-time-we-meet-again-hub And Every Time We Meet Again] series."
description-plain = "Of or related to the And Every Time We Meet Again series."

