["staff-process/"]
name = "Staff Process"
description = "These tags are added only used by SCP Wiki staff, and are intended to designate articles under staff process."

[in-rewrite]
description = "This is a temporary tag that may be placed on an article //by members of the Rewrite Team// only. It indicates the article is currently being rewritten and should be removed when said rewrite is posted. It should only be placed on articles where for reasons of site history, the original article will not be deleted before the rewrite is posted."
description-plain = "Used for pages which are currently being rewritten. Utilized by the Rewrite Team."

[rewritable]
description = "This is a temporary tag that may be be placed on an article //by members of the Rewrite Team// only. It indicates that the article is eligible to be rewritten due to circumstances falling outside the usual case of low rating and old age."
description-plain = "Used for pages which are eligible to be rewritten. Utilized by the Rewrite Team."

[rewrite]
description = "This tag indicates that the article in question is a rewrite of another article."

[deletion-range]
description = "This is a temporary tag that indicates the article is currently being voted on for deletion. It should only be placed on articles where a deletion vote has been started. Other tags should be removed when this tag is added to a page. Remove if deletion is permanently cancelled for whatever reason."
description-plain = "Used for pages which are currently being voted on for deletion."

[deletable]
description = "This is a temporary tag that indicates the article has been voted on for deletion. It should only be placed on articles where a deletion vote has been concluded. Other tags should be removed when this tag is added to a page. Remove if deletion is permanently cancelled for whatever reason."
description-plain = "Used for pages which have voted on for deletion but not yet deleted."

[featured]
description = "Designates [https://scp-wiki.wikidot.com/featured-scp-archive Featured Articles] and [https://scp-wiki.wikidot.com/featured-tale-archive Featured Tales]."
description-plain = "Used for pages which were chosen as features."

[prize-feature]
description = "Designates articles featured by the winner of a site contest."
description-plain = "Used for pages which were chosen as features by the winner of a site contest."

[reviewers-spotlight]
description = "Designates articles featured by a [https://scp-wiki.wikidot.com/reviewers-spotlight-archive forum reviewer]."
description-plain = "Used for pages which were chosen as features by forum reviewers."

[event-featured]
description = "Designates articles featured on special event days such as International Talk Like a Pirate Day."
description-plain = "Used for pages which were chosen as features on special event days."

[metadata]
description = "Designates pages with meta information about articles."
description-plain = "Used for pages which contain meta information about articles."

[_cc]
description = "This tag indicates that all images on the page in question have been demonstrated to be fully compliant with current licensing policy. __This tag should **only** be added by a member of the Licensing team__. This tag conflicts with _image."
description-plain = "Used to indicate that all images on the page are fully compliant with current licensing policy. Utilized by the Licensing Team."
supersedes = [ "_image" ]

[_image]
description = "This is a temporary tag that the tagging team applies to new articles that include one or more images, irrespective of whatever licensing information is provided by the author. This tag acts as an indicator to the Licensing team that there are images whose license status need to be confirmed and/or verified. Licensing will remove the _image tag and replace it with the _cc tag (or, if images are removed, no tag at all) when appropriate."
description-plain = "Used to indicate that not all images have been verified as being fully compliant with current licensing policy. Utilized by the Licensing Team."
conflicts = [ "_cc" ]

[_licensebox]
description = "A tag for designating that an article has a standard license info block that is tracked on the [https://scp-wiki.wikidot.com/licensing-master-list Licensing Master List]."
description-plain = "Used for pages which have a standard license info block."

[_listpages]
description = "A tag to denote that this page is an LPT article. LPT (ListPages Presented Text) means that the article presents its content through offsets served via ListPages."
description-plain = "Used for pages which present its article content through offsets served via ListPages."

[_theme-temp]
description = "Temporary tag used for marking old theme locations while they were moved from the {{component:}} category to the {{theme:}} category."
description-plain = "Used for theme pages which have been migrated from the component category to the theme category."

[crosslink]
description = "This is a temporary tag that indicates the Wikiwalk Subteam of MAST is currently proposing revisions on the page, which should be seen in the comments."
description-plain = "Used for pages which is has proposed revisions from the Wikiwalk Subteam of MAST."
