["top-level/"]
name = "Top Level"
description = "All pages on the wiki should have exactly one top-level tag that determines what kind of page it is."
max = 1

[[section]]
name = "Fictional works"
description = "The following tags are for pages that contain fiction."

[section.scp]
description = "All SCP articles from the main blocks, [https://scp-wiki.wikidot.com/scp-001 001 proposals], [https://scp-wiki.wikidot.com/joke-scps jokes] (-J), [https://scp-wiki.wikidot.com/archived-scps archives] (-ARC), and [https://scp-wiki.wikidot.com/scp-ex explained] (-EX) articles should be tagged with //scp//."
description-plain = "Used for pages which are SCP articles, including 001 proposals, jokes, and explained articles."
requires = [ [ "object-class/" ] ]

[section.goi-format]
description = "The page has been written up from the perspective of a specific Group of Interest, and conforms to the format(s) laid out in that GoI's hub page. GoI Formats should also be tagged with the tag of their GoI, as well as the underscore tag for the GoI format."
description-plain = "Used for pages which have been written up from the perspective of a specific Group of Interest, and conforms to the format(s) laid out in that GoI's hub page."
requires = [ [ "goi-format/" ] ]

[section.tale]
description = "Any fiction that is set in the SCP universe but is not an SCP, GoI Format, site page or supplement."

[section.supplement]
description = "//supplement// pages are defined as pages which require context from their parent page to understand. These pages should also have their parent page set to their originating article in order to maintain relevance and automatically create breadcrumb navigation. A page should only be tagged as //supplement// if they were created by the original author of the page, or with the original author's permission. Documents that are tributes or parodies should be tagged as //tale// instead, even if they are in the format of a log or transcript."
description-plain = "Used for pages which require context from their parent page to understand."

[section.site]
description = "//site// pages are hub pages that document specific Foundation facilities, and provide information such as the objects stored at the site, site history, assigned personnel, etc. A page tagged //site// that is also a hub page e.g. for SCPs contained within that site should also be tagged //hub//."
description-plain = "Used for pages which document specific Foundation facilities, and provide information such as the objects stored at the site, site history, assigned personnel, etc."

[[section]]
name = "Information pages"
description = "These pages contain information about the site or the writing process."

[section.guide]
description = "These pages are writing guides, helpful hints, or other pages intended to assist site users. Guides are only tagged by staff, or with staff permission. See also //essay//."
description-plain = "Used for writing guides, helpful hints, or other pages intended to assist site."

[section.essay]
description = "//essay// pages contain useful information on specific topics that may be helpful to authors writing related articles, but are different from a //guide// in that essays are subjective and reflect the author's personal opinion."
description-plain = "Used for useful information on specific topics. They are subjective and reflect the author's personal opinion."

[section.news]
description = "//news// pages contain news about the SCP Foundation in the broadest sense of the word, ranging from new artwork by fans to recently posted successful articles and everything in between. May also be used for formal announcements by staff (in as far as those aren't done on the main page or in the forum)."
description-plain = "Pages containing news, updates, or happenings on the SCP Foundation."

[section.resource]
description = "//resource// pages list various aspects of the SCP canon, optionally also adding information regarding them."
description-plain = "Pages listing aspects of the SCP canon."

[[section]]
name = "User pages"
description = "Pages for site members to showcase their body of work."

[section.author]
description = "This tag should be used for author profile pages. There should only be a single author profile page for each qualifying site member."
description-plain = "Used for author profile pages."

[section.artist]
description = "This tag should, similarly, be used for artist profile pages. If a site member wants more than one artist profile page, they must get staff permission first."
description-plain = "Used for artist profile pages. Users may have multiple with staff permission."

[section.artwork]
description = "//artwork// pages host Foundation-related artwork created by community members, whether as individual pieces or collections."
description-plain = "Used to host Foundation-related artwork created by community members, whether as individual pieces or collections."

[[section]]
name = "Import pages"
description = "These pages are designed to be imported onto other pages."

[section.component]
description = "A page that is designed to be imported onto other pages via the {{@@[[include]]@@}} syntax in order to add new design, style or functionality."
description-plain = "Used for pages intended to be imported onto other pages in order to add new design, style, or functionality."

[section.component-backend]
description = "An 'internal template' page that is designed only to be imported into other //component// or //component-backend// pages, but not used directly by authors."
description-plain = "Used for internal template pages, intended to only be imported onto other component pages."
conflicts = [ "component" ]

[section.theme]
description = "Theme pages are templates that modify the general look and feel of a page."
supersedes = [ "component" ]

[section.fragment]
description = "A page that is designed to be imported onto a single page, and contains content for that page only. They should be parented to that page. Pages of this type should be in the {{fragment:}} category and are exempt from deletion as long as their parent exists on the wiki. If they are orphaned or their parent is deleted, they are eligible for summary deletion."
description-plain = "Used for pages designed to be imported onto a single page. They should generally not be viewed directly."

[section.more-by]
description = "A page that lists works by a single author, designed to be imported onto that author's published works on the Wiki. They should be parented to that author's author page, if they have one. Pages of this type should be in the {{more-by:}} category and are exempt from voting. EN recommends that other branches do not translate these pages."
description-plain = "Used for pages that lists work by a single author, designed to be imported onto that author's published works on the Wiki."
supersedes = [ "component" ]

[[section]]
name = "Internal pages"
description = "Pages created for internal use."

[section.forum]
description = "//forum// pages are those required for internal functioning of Wikidot's forum system. They should only be created by staff."
description-plain = "Used for pages which are required for internal functioning of Wikidot's forum system."

[section.splash]
description = "//splash// pages are used as 'cover pages' for certain articles. (see: [https://scp-wiki.wikidot.com/SCP-902 SCP-902] >> [https://scp-wiki.wikidot.com/902-warning SCP-902 Warning].)"
description-plain = "Used for 'cover pages' for certain articles."

[section.redirect]
description = "//redirect// pages are those which redirect the user to a different page. They should only be created by staff or with explicit staff permission."
description-plain = "Used for pages which redirect the user to a different page."

[[section]]
name = "Other pages"

[section.admin]
description = "//admin// pages, as the name suggest, have some sort of official significance. Typically, they represent pages which are required to exist by Wikidot for some form of site functionality. They should only be created by staff."
description-plain = "Used for pages which have official significance."

[section.hub]
description = "//hub// pages are pages with a large number of links to related pages. All of the SCP series pages are //hub// pages, as are the tale index and various other pages around the site. As it is a major page tag, hubs may not have other top-level tags (e.g. //scp// or //tale//), with the exception of //contest// pages. Tale hubs should additionally be tagged with the //_tale-hub// page."
description-plain = "Used for pages with a large number of links to related pages."

[section.workbench]
description = "Workbenches are pages created by mods and admins to allow them to monitor certain pages using Wikidot's modules. While you're free to use those same monitors on your //author// page, **please do not create any workbench pages unless you're a moderator or admin**, or have received explicit permission from them to do so."
description-plain = "Used for pages created by mods and admins to utilize Wikidot modules."

[section.sandbox]
description = "In the very distant past, sandboxes on the main site were allowed. This was before the number of members became so big that the amount of sandboxes would create a total mess on the wiki. **Please note that personal sandboxes are no longer allowed on the main site.** The SCP Sandbox wiki at https://scp-sandbox-3.wikidot.com/ should be used for article drafts. Only staff may authorize new sandboxes on the site."
description-plain = "Used for pages on the site which are sandboxes."

