["translation/"]
name = "Translation"
description = "These tags indicate that the article in question has been translated to SCP-EN from one of the official SCP translation sites."

[international]
description = "Applicable if the tale or SCP article was translated from one of the recognized translation sites. Don't add this tag if the article //was// translated to another language."
description-plain = "Applicable if the tale or SCP article was translated from one of the recognized translation sites."

[[section]]
name = "Language Codes"
requires = [ "international" ]

[section._int]
description = "Translated from the [http://scp-int.wikidot.com/ International Site]."
description-plain = "Translated from the International Site."

[section._ru]
description = "Translated from the [http://scpfoundation.net/ Russian Site]."
description-plain = "Translated from the Russian Site."

[section._ko]
description = "Translated from the [http://scpko.wikidot.com/ Korean Site]."
description-plain = "Translated from the Korean Site."

[section._cn]
description = "Translated from the [http://scp-wiki-cn.wikidot.com/ Chinese Site]."
description-plain = "Translated from the Chinese Site."

[section._fr]
description = "Translated from the [http://fondationscp.wikidot.com/ French Site]."
description-plain = "Translated from the French Site."

[section._pl]
description = "Translated from the [http://scp-wiki.net.pl/ Polish Site]."
description-plain = "Translated from the Polish Site."

[section._es]
description = "Translated from the [http://lafundacionscp.wikidot.com/ Spanish Site]."
description-plain = "Translated from the Spanish Site."

[section._th]
description = "Translated from the [http://scp-th.wikidot.com/main Thai Site]."
description-plain = "Translated from the Thai Site."

[section._jp]
description = "Translated from the [http://scp-jp.wikidot.com/ Japanese Site]."
description-plain = "Translated from the Japanese Site."

[section._de]
description = "Translated from the [http://scp-wiki-de.wikidot.com/ German Site]."
description-plain = "Translated from the German Site."

[section._it]
description = "Translated from the [http://fondazionescp.wikidot.com/ Italian Site]."
description-plain = "Translated from the Italian Site."

[section._ua]
description = "Translated from the [http://scp-ukrainian.wikidot.com/ Ukrainian Site]."
description-plain = "Translated from the Ukrainian Site."

[section._pt]
description = "Translated from the [http://scp-pt-br.wikidot.com/ Portuguese Site]."
description-plain = "Translated from the Portuguese Site."

[section._zh]
description = "Translated from the [http://scp-zh-tr.wikidot.com/ Traditional Chinese Site]."
description-plain = "Translated from the Traditional Chinese Site."

[section._vn]
description = "Translated from the [http://scp-vn.wikidot.com/ Vietnamese Site]."
description-plain = "Translated from the Vietnamese Site."

[section._el]
description = "Translated from the [http://scp-el.wikidot.com/ Greek Site]."
description-plain = "Translated from the Greek Site."
