["canons/"]
name = "Canons"
description = "Tags for canons from the Canon Hub and the articles that take place in their setting."

[aiad]
description = "Of or related to the [http://scp-wiki.wikidot.com/aiad-homescreen AIAD] canon."

[ad-astra]
description = "Of or related to the [http://www.scp-wiki.net/ad-astra-per-aspera-hub Ad Astra Per Aspera] canon."

[aces-and-eights]
description = "Of or related to the [http://www.scp-wiki.net/aces-and-eights Aces and Eights] canon."

[alchemy-department]
description = "Of or related to [http://www.scp-wiki.net/the-alchemy-department-hub The Alchemy Department] canon."

[antarctic-exchange]
description = "Of or related to the [http://scp-wiki.wikidot.com/antarctic-exchange-hub Antarctic Exchange] canon."

[apotheosis]
description = "Of or related to the [http://scp-wiki.wikidot.com/antarctic-exchange-hub Apotheosis] canon."

[bellerverse]
description = "Of or related to the [http://scp-wiki.wikidot.com/bellerverse Bellerverse] canon."

[black-rabbit-company]
description = "Of or related to the [http://scp-wiki.wikidot.com/stealingsolidarityhub Stealing Solidarity] canon."

[broken-masquerade]
description = "Of or related to the [http://scp-wiki.wikidot.com/broken-masquerade-hub Broken Masquerade] canon."

[competitive-eschatology]
description = "Of or related to the [http://scp-wiki.wikidot.com/Competitive-Eschatology-Hub Competitive Eschatology] canon."

[cool-war-2]
description = "Of or related to the [http://www.scp-wiki.net/cool-war-2-hub Cool War 2: Ruiz From Your Grave] canon."

[doctors-of-the-church]
description = "Of or related to the [http://www.scp-wiki.net/doctors-of-the-church-hub Doctors of the Church] canon."

[dread&circuses]
description = "Of or related to the [http://www.scp-wiki.net/dread-circuses-hub Dread and Circuses] canon."

[deepwell-catalog]
description = "Of or related to the [http://scp-wiki.wikidot.com/site-17-hub Site-17 Deepwell] canon."

[end-of-death]
description = "Of or related to the [http://www.scp-wiki.net/end-of-death-hub End of Death] canon."

[etdp]
description = "Of or related to the [http://scp-wiki.wikidot.com/etdp-hub-page Et Tam Deum Petivi] canon."

[green-king]
description = "Of or related to the [http://scp-wiki.wikidot.com/codename-green-king-hub Codename: Green King hub]."

[insect-hell]
description = "Of or related to the [http://scp-wiki.wikidot.com/arbh-class-hub insect hell] canon."

[lolfoundation]
description = "Of or related to the [http://scp-wiki.wikidot.com/lolfoundation-hub-page lolFoundation] canon."

[memoria-adytum]
description = "Of or related to the [http://scp-wiki.wikidot.com/memoria-adytum In Memoria, Adytum] canon."

[old-man-in-the-sea]
description = "Of or related to the [http://scp-wiki.wikidot.com/old-man-in-the-sea-hub Old Man in the Sea] canon."

[on-mount-golgotha]
description = "Of or related to the [http://www.scp-wiki.net/on-mount-golgotha-hub On Mount Golgotha] canon."

[only-game-in-town]
description = "Of or related to the [http://www.scp-wiki.net/only-game-in-town-hub Only Game in Town] canon."

[orcadia]
description = "Of or related to the Seas of Orcadia canon."

[heimdall]
description = "Of or related to [http://scp-wiki.wikidot.com/Project-Heimdall Project Heimdall]."

[rats-nest]
description = "Of or related to the [http://scp-wiki.wikidot.com/rat-s-nest-hub Rat's Nest] canon."

[resurrection]
description = "Of or related to the [http://www.scp-wiki.net/resurrection Resurrection] project."

[s&c-plastics]
description = "Of or related to the [http://scp-wiki.wikidot.com/the-s-c-plastics-hub S & C Plastics] canon."

[ship-in-a-bottle]
description = "Of or related to the [http://scp-wiki.wikidot.com/siabhub Ship In A Bottle] canon."

[sotm]
description = "Of or related to the [http://scp-wiki.wikidot.com/sotmhub Straight On Till Morning] canon."

[the-coldest-war]
description = "Of or related to the [http://www.scp-wiki.net/the-coldest-war-hub Coldest War] canon."

[the-gulf]
description = "Of or related to [http://scp-wiki.wikidot.com/The-Gulf The Gulf] canon."

[man-who-wasnt-there]
description = "Of or relating to [http://www.scp-wiki.net/the-man-who-wasnt-there-hub The Man Who Wasn't There] canon."

[the-trashfire]
description = "Of or relating to [http://www.scp-wiki.net/the-trashfire The Trashfire] canon."

[third-law]
description = "Of or pertaining to the [http://www.scp-wiki.net/third-law-hub Third Law] canon."

[twisted-pines]
description = "Of or related to the [http://scp-wiki.wikidot.com/those-twisted-pines-hub Those Twisted Pines] canon."

[unfounded]
description = "Of or related to the [http://www.scp-wiki.net/unfounded-hub Unfounded] canon."

[war-on-all-fronts]
description = "Of or related to the [http://www.scp-wiki.net/war-on-all-fronts-hub War On All Fronts] canon."

[wonderful-world]
description = "Of or related to the [http://www.scp-wiki.net/wonder-world What a Wonderful World] canon."
