["goi-format/"]
description = "These are tags for GoI formats that describe which GoI the page is formatted for. There should be one tag for each GoI; however, only GoIs for which GoI Format articles exist are listed here. If there is a GoI Format article in the format of a GoI that does not have a tag, it should be tagged //_other//. Additionally, if the corresponding tag for a GoI format does not exist but there is an article that should have it, please contact staff to request it."

[_alexylva]
description = "An article following the Alexylva Universiy format."
requires = [ "alexylva" ]

[_ambrose-restaurant]
description = "An article following the Ambrose Restaurants format."
requires = [ "ambrose-restaurant" ]

[_anderson]
description = "An article following the Anderson Robotics format."
requires = [ "anderson" ]

[_arcadia]
description = "An article following the Arcadia format."
requires = [ "arcadia" ]

[_are-we-cool-yet]
description = "An article following the Are We Cool Yet? format."l
requires = [ "are-we-cool-yet" ]

[_black-queen]
description = "An article following the Black Queen format."
requires = [ "black-queen" ]

[_broken-god]
description = "An article following the Church of the Broken God format."
requires = [ "broken-god" ]

[_chaos-insurgency]
description = "An article following the Chaos Insurgency format."
requires = [ "chaos-insurgency" ]

[_chicago-spirit]
description = "An article following the Chicago Spirit format."
requires = [ "chicago-spirit" ]

[_deer-college]
description = "An article following the Deer College format."
requires = [ "deer-college" ]

[_factory]
description = "An article following the Factory format."
requires = [ "factory" ]

[_fifthist]
description = "An article following the Fifthist format."
requires = [ "fifthist" ]

[_global-occult-coalition]
description = "An article following the Global Occult Coalition format."
requires = [ "global-occult-coalition" ]

[_gru-division-p]
description = "An article following the GRU Division P format."
requires = [ "gru-division-p" ]

[_herman-fuller]
description = "An article following the Herman Fuller format."
requires = [ "herman-fuller" ]

[_horizon-initiative]
description = "An article following the Horizon Initiative format."
requires = [ "horizon-initiative" ]

[_ijamea]
description = "An article following the IJAMEA format."
requires = [ "ijamea" ]

[_la-rue-macabre]
description = "An article following the La Rue Macabre format."
requires = [ "la-rue-macabre" ]

[_manna-charitable-foundation]
description = "An article following the Manna Charitable Foundation format."
requires = [ "manna-charitable-foundation" ]

[_marshall-carter-and-dark]
description = "An article following the Marshall, Carter and Dark format."
requires = [ "marshall-carter-and-dark" ]

[_medicea-accademia]
description = "An article following the Medicea Accademia format."
requires = [ "medicea-accademia" ]

[_nobody]
description = "An article following the Nobody format."
requires = [ "nobody" ]

[_oneiroi]
description = "An article following the Oneiroi format."
requires = [ "oneiroi" ]

[_other]
description = "A GoI Format following a format not associated with a tagged Group of Interest."

[_prometheus]
description = "An article following the Prometheus format."
requires = [ "prometheus" ]

[_reclamation]
description = "An article following the Reclamation format."
requires = [ "reclamation" ]

[_sapphire]
description = "An article following the SAPPHIRE format."
requires = [ "sapphire" ]

[_second-hytoth]
description = "An article following the Second Hytoth format."
requires = [ "second-hytoth" ]

[_serpents-hand]
description = "An article following the Serpents' Hand format."
requires = [ "serpents-hand" ]

[_shark-punching-center]
description = "An article following the Shark Punching Center format."
requires = [ "shark-punching-center" ]

[_three-moons-initiative]
description = "An article following the Three Moons Initiative format."
requires = [ "three-moons-initiative" ]

[_unusual-incidents-unit]
description = "An article following the Unusual Incidents Unit format."
requires = [ "unusual-incidents-unit" ]

[_wilsons-wildlife]
description = "An article following the Wilsons' Wildlife format."
requires = [ "wilsons-wildlife" ]
