["major-goi/"]
description = "These tags are used to designate pages that prominently feature a major Group of Interest, and can be applied to any fictional page type."

[alexylva]
description = "Of or related to the Alexylva University group of interest."

[ambrose-restaurant]
description = "Of or related to the Ambrose Restaurant."

[anderson]
description = "Of or related to the Anderson Robotics group of interest."

[are-we-cool-yet]
description = "Of or related to the Are We Cool Yet? (AWCY) group of interest."

[asci]
description = "Of or related to the American Secure Containment Initiative."

[black-queen]
description = " Of or related to the Black Queen group of interest."

[broken-god]
description = " Of or related to Mekhane, or the Church of the Broken God (CotBG) group of interest."

[chaos-insurgency]
description = "Of or related to the Chaos Insurgency (CI) group of interest."

[chicago-spirit]
description = "Of or related to the Chicago Spirit group of interest."

[daevite]
description = "Of or related to the Daevites."

[deer-college]
description = "Of or related to the Deer College SCPs and stories in the Three Portlands setting."

[dr-wondertainment]
description = "Of or related to the Dr. Wondertainment individual or group of interest."

[factory]
description = "Of or is related to The Factory group of interest."

[fifthist]
description = "Of or related to The Fifthist Church group of interest."

[gamers-against-weed]
description = "Of or related to The Gamers Against Weed group of interest."

[global-occult-coalition]
description = "Of or related to the Global Occult Coalition (GOC) group of interest."

[gru-division-p]
description = "Of or related to the GRU Division "P" group of interest."

[herman-fuller]
description = "Of or related to the Herman Fuller's Circus of the Disquieting group of interest."

[horizon-initiative]
description = "Of or related to the Horizon Initiative group of interest."

[ijamea]
description = "Of or related to the Imperial Japanese Anomalous Matters Examination Agency"

[mages-academy]
description = "Of or related to the Mages Academy group of interest."

[manna-charitable-foundation]
description = "Of or related to the Manna Charitable Foundation group of interest."

[marshall-carter-and-dark]
description = "Of or related to the Marshall, Carter, and Dark Ltd. (MC&D) group of interest."

[medicea-accademia]
description = "Of or related to the Italian GoI Medicean Academy of Occult Art (Medicea Accademia Dell'Arte Occulta)."

[nobody]
description = "Of or related to the 'Nobody' group of interest."

[oneiroi]
description = "Of or related to the Oneiroi Collective group of interest."

[parawatch]
description = "Of or related to the Parawatch Wiki."

[prometheus]
description = "Of or related to the Prometheus Labs group of interest."

[reclamation]
description = "Of or related to the Office For The Reclamation of Islamic Artifacts (ORIA) group of interest. "

[sapphire]
description = "Of or related to the SAPPHIRE group of interest. "

[sarkic]
description = "Of or related to the Sarkic Cults group of interest."

[second-hytoth]
description = "Of or related to the Church of the Second Hytoth group of Interest."

[serpents-hand]
description = "Of or related to the Serpent's Hand group of interest."

[shark-punching-center]
description = "Of or related to the Shark Punching Center."

[three-moons-initiative]
description = "Of or related to the Three Moons Initiative."

[unusual-incidents-unit]
description = "Of or related to the Federal Bureau of Investigation Unusual Incidents Unit (UIU) group of interest."

[wilsons-wildlife]
description = "Of or related to the Wilson's Wildlife organization."
