["minor-goi/"]
name = "Minor GoIs"
description = "These tags are used to designate pages that prominently feature a minor Group of Interest, and can be applied to any fictional page type."

[arcadia]
description = "Of or related to the ##purple|Arcadia## organization."

[accelerate-the-future]
description = "Of or related to Accelerate the Future"

[blackwood]
description = "Of or related to The Adventures of Lord Blackwood, Explorer and Gentleman."

[brothers-of-death]
description = "Of or related to the Brothers of Death canon or characers."

[children-of-the-torch]
description = "SCP is of or related to the Children of the Torch group of Interest."

[children-of-the-night]
description = "Of or related to the Children of the Night, outlined in [https://scp-wiki.wikidot.com/scp-1000 SCP-1000]."

[class-of-76]
description = "Of or related to the [http://scp-wiki.wikidot.com/Remembrance  Class of '76] SCPs and stories."

[decommissioning-dept]
description = "Of or related to the Decommissioning Department."

[miscommunications]
description = "Of or related to the [http://scp-wiki.wikidot.com/domc-hub Department of Miscommunications]."

[nameless]
description = "Of or related to the Nameless, or the Fae, outlined in [https://scp-wiki.wikidot.com/scp-4000 SCP-4000]."

[ethics-committee]
description = "Of or related to the Foundation Ethics Committee."

[obskura]
description = "Of or related to the Obskura Corps GoI"

[pangloss]
description = "Of or related to the Pangloss individual of interest."

[pattern-screamer]
description = "Of or related to pattern screamers."

[pentagram]
description = "Of or related to Pentagram."

[pitch-haven]
description = "Of or related to the Pitch Haven series of SCPs and tales."

[professor-aw]
description = "Of or related to the inventions and curiosities of one Professor A. W."

[sugarcomb-confectionery]
description = "Of or related to Sugarcomb Confectionery."

[tactical-theology]
description = "Of or related to the Department of Tactical Theology"

[west-head-media]
description = "Of or related to the Westhead Media group of interest."

[xia-dynasty]
description = "Of or related to the Xia Dynasty."

